/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_semux_evmc_jni_Native */

#ifndef _Included_org_semux_evmc_jni_Native
#define _Included_org_semux_evmc_jni_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_semux_evmc_jni_Native
 * Method:    create_evmjit
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_semux_evmc_jni_Native_create_1evmjit
  (JNIEnv *, jclass);

/*
 * Class:     org_semux_evmc_jni_Native
 * Method:    create_example_evm
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_semux_evmc_jni_Native_create_1example_1evm
  (JNIEnv *, jclass);

/*
 * Class:     org_semux_evmc_jni_Native
 * Method:    set_option
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_org_semux_evmc_jni_Native_set_1option
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_semux_evmc_jni_Native
 * Method:    execute
 * Signature: (Lorg/semux/evmc/jni/Context;I[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_semux_evmc_jni_Native_execute
  (JNIEnv *, jclass, jobject, jint, jbyteArray, jbyteArray);

/*
 * Class:     org_semux_evmc_jni_Native
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_semux_evmc_jni_Native_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
